language: csharp
solution: phaxio-dotnet.sln
install:
  - nuget restore phaxio-dotnet.sln
  - nuget install NUnit.Runners -Version 2.6.3 -OutputDirectory tools
script:
  - xbuild /p:Configuration=Release phaxio-dotnet.sln /p:TargetFrameworkVersion="v4.5"
  - mono ./tools/NUnit.Runners.2.6.3/tools/nunit-console.exe ./Phaxio.Tests/bin/Release/Phaxio.Tests.dll